Bug 583704 – undefined reference to `gdu_error_check_polkit_not_authorized'
With the new polkit 1.0 version that gnome-disk-utility is now using,
authorizations are obtained out-of-band. So we don't need to handle it
here.