common: Check BDMV folder before libblueray usage
You can see the following errors from libblueray if you insert
non-blueray disk:
disc.c:350: error opening file BDMV/index.bdmv
disc.c:350: error opening file BDMV/BACKUP/index.bdmv

Unfortunately bd_set_debug_mask is not part of public API, so we
have no control over the output. Let's do not use any libblueray
API functions if BDMV dir does not exists to avoid such errors.

https://bugzilla.gnome.org/show_bug.cgi?id=767909